USE cs340_peterkom;
CREATE TABLE Contains(
   id           INTEGER PRIMARY KEY
  ,ingredient0  VARCHAR(15) NOT NULL
  ,ingredient1  VARCHAR(14)
  ,ingredient2  VARCHAR(14)
  ,ingredient3  VARCHAR(15)
  ,ingredient4  VARCHAR(14)
  ,ingredient5  VARCHAR(17)
  ,ingredient6  VARCHAR(17)
  ,ingredient7  VARCHAR(17)
  ,ingredient8  VARCHAR(15)
  ,ingredient9  VARCHAR(13)
  ,ingredient10 VARCHAR(12)
  ,ingredient11 VARCHAR(13)
  ,ingredient12 VARCHAR(15)
  ,ingredient13 VARCHAR(15)
  ,ingredient14 VARCHAR(10)
  ,FOREIGN KEY(id)REFERENCES Recipes(id)
  ,UNIQUE(id)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (100,'Tomato','Peppers','Cucumber','Olive-Oil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (200,'Chicken','Black-Pepper','Eggs','Parmesan-Cheese','Olive-Oil','Tomato','Flour','Mozzarella-Cheese','Basil','Bread-Crumbs',NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (300,'Vegetable-Oil','Vinegar','Black-Pepper','Zucchini','Green-Beans','Salt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (400,'Bacon','Lettuce','Tomato','Bread','Mayonnaise',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (500,'Butter','Bread','Cheddar-Cheese',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (600,'Mayonnaise','Greek-Yogurt','Lemon','Chicken','Celery','Mozzarella-Cheese','Parsley','Black-Pepper','Salt','Dijon-Mustard',NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (700,'Bacon','Beef','Salt','Cheddar-Cheese',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (800,'Olive-Oil','Garlic','Salt','Tomato','Basil','Pasta','Parmesan-Cheese','Black-Pepper',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (900,'Beef','Hamburger-Buns','Cheese','Lettuce','Tomato',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1000,'Pasta','Garlic','Olive-Oil','Bacon','Parsley','Eggs','Parmesan-Cheese','Black-Pepper',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1100,'Olive-Oil','Garlic','Salt','Tomato','Carrot','Pasta','Tomato-Paste','Black-Pepper','Onion','Sausage','Parsley',NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1200,'Olive Oil','Garlic','Salt','Tomato','Carrot','Pasta','Tomato-Paste','Black-Pepper','Onion','Beef','Red-Wine','Celery','Bay-Leaf','Parmesan-Cheese',NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1300,'Butter','Carrot','Celery','Peppers','Garlic','Rice','Corn','Chicken-Broth','Onion','Beef','Red-Wine','Parsley','Bay-Leaf','Peas',NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1400,'Mayonnaise','Celery','Onion','Tuna','Bread','Lettuce',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1500,'Mayonnaise','Celery','Onion','Tuna',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1600,'Olive-Oil','Chicken','Salt','Flour','Egg','Bread-Crumbs','Paprika','Lemon',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1700,'Olive-Oil','Tomato','Salt','Flour','Shrimp','Bread-Crumbs','Paprika','Garlic','Vinegar','Basil','Black-Pepper',NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1800,'Black-Pepper','Chicken','Salt','Swiss-Cheese','Ham','Bread-Crumbs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (1900,'Egg','Avacado','Bacon','Cheddar-Cheese','Bread',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2000,'Egg','Bacon','Cheddar-Cheese','Bread',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2100,'Pasta','Butter','Flour','Milk','Sour-Cream','Cheddar-Cheese','Salt','Black-Pepper',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2200,'Beef','Butter','Egg','Potatoe','Cheddar-Cheese','Salt','Black-Pepper','Hamburger-Buns',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2300,'Potatoe','Butter','Paprika','Salt','Black-Pepper',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2400,'Brussel-Sprouts','Bacon','Salt','Black-Pepper',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2500,'Potato','Chicken','Olive-Oil','Black-Pepper','Onion','Salt','Carrot','Celery','Butter','Flour','Milk','Chicken-Broth','Bacon','Cheddar-Cheese','Sour-Cream');
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2600,'Basil','Tomato','Olive-Oil','Black-Pepper','Onion','Salt','Bread-Crumbs','Egg','Parmesan-Cheese','Flour','Bacon','Beef',NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2700,'Sausage','Bacon','Olive-Oil','Black-Pepper','Onion','Salt','Carrot','Butter','Chicken-Broth','Potato','Milk','Celery','Garlic',NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2800,'Chicken','Peppers','Olive-Oil','Black-Pepper','Onion','Salt','Carrot','Parsley','Chicken-Broth','Potato','Garlic','Celery','Parmesan-Cheese','Tomato','Pasta');
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (2900,'Egg','Onion','Butter','flour','Milk','Cheddar-Cheese','Salt','Peppers','Pasta',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3000,'Egg','Tomato','Avacado','Black-Pepper','Onion','Salt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3100,'Chicken','Butter','Olive-Oil','Flour','Milk','Chicken-Broth','Lemon','Black-Pepper','Salt',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3200,'Egg','Milk','Onion','Bacon','Butter','Cheddar-Cheese','Salt','Black-Pepper',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3300,'Egg','Milk','Flour','Vegetable-Oil','Bacon','Salt','Black-Pepper',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3400,'Egg','Cheddar-Cheese','Avocado','Olive-Oil','Tomato','Salt','Black-Pepper',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3500,'Broccoli','Butter','Flour','Milk','Cheddar-Cheese','Salt','Black-Pepper',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3600,'Beef','Vegetable-Oil','Butter','Flour','Milk','Salt','Egg',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3700,'Egg','Onion','Milk','Sausage','Salt','Black-Pepper','Flour',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3800,'Potato','Olive-Oil','Butter','Garlic','Salt','Black-Pepper','Lemon',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (3900,'Potato','Olive-Oil','Butter','Garlic','Salt','Black-Pepper','Milk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (4000,'Egg','Olive-Oil','Butter','Garlic','Salt','Black-Pepper','Lemon','Parsley',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (4100,'Squash','Olive-Oil','Parsley','Garlic','Black-Pepper','Lemon',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (4200,'Squash','Olive-Oil','Peppers','Onion','Salt','Black-Pepper','Mozzarella-Cheese','Parmesan-Cheese',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (4300,'Chicken-Broth','Olive-Oil','Squash','Onion','Salt','Black-Pepper','Turkey','Parmesan-Cheese','Pasta','Thyme',NULL,NULL,NULL,NULL,NULL);
INSERT INTO Contains(id,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14) VALUES (4400,'Pickle',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
