USE cs340_peterkom;
CREATE TABLE Ingredients(
   id         INTEGER AUTO_INCREMENT PRIMARY KEY
  ,name       VARCHAR(17) NOT NULL
  ,food_group VARCHAR(15) NOT NULL
  ,UNIQUE(id)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO Ingredients(id,name,food_group) VALUES (101,'Beef','Meats');
INSERT INTO Ingredients(id,name,food_group) VALUES (111,'Turkey','Meats');
INSERT INTO Ingredients(id,name,food_group) VALUES (121,'Chicken-Breast','Meats');
INSERT INTO Ingredients(id,name,food_group) VALUES (131,'Bacon','Meats');
INSERT INTO Ingredients(id,name,food_group) VALUES (141,'Ham','Meats');
INSERT INTO Ingredients(id,name,food_group) VALUES (151,'Sausage','Meats');
INSERT INTO Ingredients(id,name,food_group) VALUES (161,'Bison','Meats');
INSERT INTO Ingredients(id,name,food_group) VALUES (171,'Shrimp','Meats');
INSERT INTO Ingredients(id,name,food_group) VALUES (181,'Tuna','Meats');
INSERT INTO Ingredients(id,name,food_group) VALUES (202,'Lettuce','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (212,'Zucchini','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (222,'Broccoli','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (232,'Tomato','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (242,'Brussle Sprouts','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (252,'Carrot','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (262,'Onion','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (272,'Peppers','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (282,'Cabbage','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (292,'Corn','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (203,'Squash','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (213,'Cucumber','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (223,'Celery','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (233,'Garlic','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (243,'Avacado','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (253,'Pickle','Vegetables');
INSERT INTO Ingredients(id,name,food_group) VALUES (303,'Cheddar-Cheese','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (313,'Mozzarella-Cheese','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (323,'Parmesan-Cheese','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (333,'Swiss-Cheese','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (343,'Milk','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (353,'Yogurt','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (363,'Greek-Yogurt','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (373,'Butter','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (383,'Sour-Cream','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (393,'Cottage-Cheese','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (304,'Egg','Dairy');
INSERT INTO Ingredients(id,name,food_group) VALUES (404,'Rice','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (414,'Quinoa','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (424,'Pasta','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (434,'Hamburger-Bun','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (444,'Oats','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (454,'Barley','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (464,'Bread','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (474,'Flour','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (484,'Potato','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (494,'Bread-Crumbs','Grains');
INSERT INTO Ingredients(id,name,food_group) VALUES (505,'Salt','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (515,'Black-Pepper','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (525,'Lemon','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (535,'Basil','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (545,'Parsley','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (555,'Tomato-Paste','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (565,'Bay-Leaf','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (575,'Red-Wine','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (585,'Chicken-Broth','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (595,'Paprika','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (506,'Thyme','Seasonings');
INSERT INTO Ingredients(id,name,food_group) VALUES (606,'Salad-Dressing','Oils&Condiments');
INSERT INTO Ingredients(id,name,food_group) VALUES (616,'Vinegar','Oils&Condiments');
INSERT INTO Ingredients(id,name,food_group) VALUES (626,'Olive-Oil','Oils&Condiments');
INSERT INTO Ingredients(id,name,food_group) VALUES (636,'Vegetable-Oil','Oils&Condiments');
INSERT INTO Ingredients(id,name,food_group) VALUES (646,'Cocnut-Oil','Oils&Condiments');
INSERT INTO Ingredients(id,name,food_group) VALUES (656,'Peanut-Butter','Oils&Condiments');
INSERT INTO Ingredients(id,name,food_group) VALUES (666,'Mayonnaise','Oils&Condiments');
INSERT INTO Ingredients(id,name,food_group) VALUES (676,'Dijon-Mustard','Oils&Condiments');
INSERT INTO Ingredients(id,name,food_group) VALUES (707,'Green-Beans','Legumes');
INSERT INTO Ingredients(id,name,food_group) VALUES (717,'Peas','Legumes');
INSERT INTO Ingredients(id,name,food_group) VALUES (727,'Black-Beans','Legumes');
INSERT INTO Ingredients(id,name,food_group) VALUES (737,'Lentils','Legumes');
INSERT INTO Ingredients(id,name,food_group) VALUES (747,'Chickpeas','Legumes');
INSERT INTO Ingredients(id,name,food_group) VALUES (757,'Kidney-Beans','Legumes');
